-- Add social profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_twitter TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_github TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_linkedin TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_facebook TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_instagram TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS social_youtube TEXT DEFAULT '';
